# =============================================================================
# First Order blade pack — presets
# =============================================================================
# Copy to SD: config/presets.ini
# =============================================================================

new_preset
font = SmthJedi
font_overlay = font/KyloRen
track = tracks/hum.wav
style = config fo_kylo_unstable
name = KyloRen
variation = 0

end
