/**
 * LayerBlade product naming for UI and exported INI headers.
 *
 * @module brand
 */
export const PRODUCT_NAME = 'LayerBlade';

/** Shown in app bar and page titles. */
export const PRODUCT_TAGLINE = 'SD blade styles for ProffieOS';

export const PRODUCT_FULL = `${PRODUCT_NAME} · ${PRODUCT_TAGLINE}`;

/** First-line comment in exported INI files. */
export const INI_GENERATED_BY = `Generated by ${PRODUCT_NAME} browser editor (frontend-only).`;
