/**
 * Serialize style sections to `config/blade_styles.ini` text.
 *
 * @module serialize/bladeStylesIni
 */
import { exportColorToken } from '../model/colors';
import type { StyleLayer, StyleSection } from '../model/style-sections';
import { resolveLayerArgs, resolveVarTemplate } from '../model/style-sections';
import { blankLine, iniHeader } from './format';

function exportToken(value: string): string {
  return exportColorToken(value);
}

const FULL_OPACITY = 32768;

function serializeLayerLine(layer: StyleLayer, vars: Record<string, string>): string {
  const tokens: string[] = [];

  if (layer.blend !== 'normal') {
    tokens.push(layer.blend);
  }

  if (layer.opacity < FULL_OPACITY) {
    tokens.push('opacity', String(layer.opacity));
  }

  if (layer.styleName === 'config') {
    tokens.push('config', layer.configSection ?? '');
  } else {
    tokens.push(
      layer.styleName,
      ...resolveLayerArgs(layer, vars).map((arg) => exportToken(arg)),
    );
  }

  return `layer = ${tokens.join(' ')}`.trimEnd();
}

function serializeSectionBlock(section: StyleSection): string[] {
  const lines: string[] = [`[${section.id}]`];

  const reserved = new Set(['version']);
  for (const [key, value] of Object.entries(section.vars)) {
    if (reserved.has(key)) {
      continue;
    }
    lines.push(`${key} = ${exportToken(resolveVarTemplate(value, section.vars))}`);
  }

  for (const layer of section.layers) {
    lines.push(serializeLayerLine(layer, section.vars));
  }

  return lines;
}

/**
 * Generate `blade_styles.ini` from all sections.
 *
 * @param sections - Ordered section list
 */
export function serializeBladeStylesIni(sections: StyleSection[]): string {
  const header = iniHeader('config/blade_styles.ini - Config file styles (layer stacks)', [
    'Copy this file to the root of your SD card as:  config/blade_styles.ini',
    '',
    'Generated by ProffieOS SD Config Editor (frontend-only).',
    'See examples/config/blade_styles.ini for layer grammar.',
  ]);

  const body: string[] = [];

  for (const section of sections) {
    body.push(`# ---- [${section.id}] ----`);
    body.push(...serializeSectionBlock(section));
    body.push(blankLine());
  }

  return `${header}\n${body.join('\n')}\n`;
}
