/**
 * Serialize {@link BladeDefinition}[] to `config/blades.ini` text.
 *
 * Output matches conventions in `examples/config/blades.ini` and `doc/blade_config.md`:
 * - NeoPixel: `data_pin`, `pixels`, `power_pin` or `power_pin1`…
 * - Simple: `type = simple`, `data_pin`, `led`, `active_state`
 * - Terminates with `end`
 *
 * @module serialize/bladesIni
 */
import type { BladeDefinition } from '../model/blades';
import { boardPinReferenceLabel } from '../model/data-pins';
import { exportablePowerPins } from '../model/power-pins';
import { blankLine, iniHeader } from './format';

/** Build INI lines for one `blade = N` … block (without trailing blank line). */
function serializeBladeBlock(blade: BladeDefinition): string[] {
  const lines: string[] = [];

  const boardLabel = boardPinReferenceLabel(blade.dataPin);
  if (boardLabel) {
    lines.push(`# ---- ${boardLabel} ----`);
  }

  lines.push(`blade = ${blade.index}`);

  if (blade.type === 'simple') {
    lines.push('type = simple');
    lines.push(`data_pin = ${blade.dataPin}`);
    if (blade.led) {
      lines.push(`led = ${blade.led}`);
    }
    if (blade.activeState) {
      lines.push(`active_state = ${blade.activeState}`);
    }
  } else {
    lines.push(`data_pin = ${blade.dataPin}`);
    if (blade.pixels != null) {
      lines.push(`pixels = ${blade.pixels}`);
    }
    const pins = exportablePowerPins(blade.powerPins);
    if (pins.length === 1) {
      lines.push(`power_pin = ${pins[0]}`);
    } else if (pins.length > 1) {
      pins.forEach((pin, i) => {
        lines.push(`power_pin${i + 1} = ${pin}`);
      });
    }
  }

  return lines;
}

/**
 * Generate full `blades.ini` contents from the wiring store.
 *
 * Blades are sorted by index ascending before export.
 */
export function serializeBladesIni(blades: BladeDefinition[]): string {
  const header = iniHeader('config/blades.ini - Blade wiring (data pin, pixels, power pins)', [
    'Copy this file to the root of your SD card as:  config/blades.ini',
    '',
    'Generated by ProffieOS SD Config Editor (frontend-only).',
    'See doc/blade_config.md for full grammar.',
  ]);

  const body: string[] = [];
  const sorted = [...blades].sort((a, b) => a.index - b.index);

  for (const blade of sorted) {
    body.push(...serializeBladeBlock(blade));
    body.push(blankLine());
  }

  body.push('# ---- Required: end of blade definitions ----');
  body.push('end');

  return `${header}\n${body.join('\n')}\n`;
}
