/**
 * Serialize board hardware options to `config/board.ini`.
 *
 * @module serialize/boardIni
 */
import type { BoardFeaturesState } from '../model/board';
import { iniHeader } from './format';

function onOff(value: boolean): string {
  return value ? 'on' : 'off';
}

/** Generate `board.ini` contents. */
export function serializeBoardIni(state: BoardFeaturesState): string {
  const header = iniHeader('config/board.ini - Board hardware configuration', [
    'Copy this file to the root of your SD card as:  config/board.ini',
    '',
    'Generated by ProffieOS SD Config Editor (frontend-only).',
    'Gesture/twist values here are overridden by config/features.ini when present.',
  ]);

  const body = [
    'buttons = ' + state.buttons,
    'oled = ' + onOff(state.oled),
    'bluetooth = ' + onOff(state.bluetooth),
    '',
    '# Optional — overridden by config/features.ini when that file exists',
    'gesture = ' + onOff(state.gesture),
    'twist_on = ' + onOff(state.twistOn),
    'twist_off = ' + onOff(state.twistOff),
  ];

  return `${header}\n${body.join('\n')}\n`;
}
