/**
 * Serialize feature toggles to `config/features.ini`.
 *
 * @module serialize/featuresIni
 */
import { contextLogger } from '../logger';
import type { BoardFeaturesState } from '../model/board';
import { iniHeader } from './format';

function onOff(value: boolean): string {
  return value ? 'on' : 'off';
}

/** Generate `features.ini` contents (gesture + twist only). */
export function serializeFeaturesIni(state: BoardFeaturesState): string {
  contextLogger('featuresIni', 'serializeFeaturesIni').debug('export', {
    gesture: state.gesture,
    twistOn: state.twistOn,
  });
  const header = iniHeader('config/features.ini - Feature toggles (gesture, twist)', [
    'Copy this file to the root of your SD card as:  config/features.ini',
    '',
    'Generated by ProffieOS SD Config Editor (frontend-only).',
    'Values here override gesture/twist keys from config/board.ini.',
  ]);

  const body = [
    'gesture = ' + onOff(state.gesture),
    'twist_on = ' + onOff(state.twistOn),
    'twist_off = ' + onOff(state.twistOff),
  ];

  return `${header}\n${body.join('\n')}\n`;
}
