/**
 * Serialize preset definitions to `config/presets.ini` text.
 *
 * @module serialize/presetsIni
 */
import type { PresetDefinition } from '../model/presets';
import { formatPresetStyleLine } from '../model/preset-styles';
import { iniHeader } from './format';

function commentBlock(text: string | undefined): string[] {
  if (!text?.trim()) {
    return [];
  }
  return [`# ${text.trim()}`];
}

function serializePreset(preset: PresetDefinition): string[] {
  const lines: string[] = [
    ...commentBlock(preset.comment),
    'new_preset',
    'font = ' + preset.font.trim(),
    'track = ' + preset.track.trim(),
    ...preset.styles.map((style) => 'style = ' + formatPresetStyleLine(style)),
    'name = ' + preset.name.trim(),
    'variation = ' + preset.variation,
    '',
  ];
  return lines;
}

/** Generate full `presets.ini` contents. */
export function serializePresetsIni(presets: PresetDefinition[]): string {
  const header = iniHeader('config/presets.ini - Preset list (font, track, style, name)', [
    'Copy this file to the root of your SD card as:  config/presets.ini',
    '',
    'One style = line per logical blade index. Match NUM_BLADES and blades.ini wiring.',
    'Use config <section> for recipes in config/blade_styles.ini.',
    '',
    'Generated by ProffieOS SD Config Editor (frontend-only).',
  ]);

  const body = presets.flatMap((preset) => serializePreset(preset));
  body.push('end', '');

  return `${header}\n${body.join('\n')}`;
}
